require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe HousesController do
  render_views
  
  describe "GET index" do
    before(:each) do
      @house = Factory :house
    end

    it "should be a success" do
      visit houses_path
      response.should be_success
    end

    it "should show the houses" do
      visit houses_path
      page.should have_selector('tr.house')
    end
  end

  describe "GET show" do
    before(:each) do
      @house = Factory :house
    end

    it "should be a success" do
      visit house_path(@house)
      response.should be_success
    end

    it "should show the house's details" do
      visit house_path(@house)
      page.should have_content(@house.title)
    end
  end

  describe "GET new" do
    before(:each) do
      @house = Factory :house
    end

    it "should be a success" do
      visit new_house_path
      response.should be_success
    end

    it "should have a form to fill in the house's details" do
      visit new_house_path
      page.should have_selector('form#new_house')
    end
  end

  describe "GET edit" do
    before(:each) do
      @house = Factory :house
    end

    it "should be a success" do
      get 'edit', :id => @house
      response.should be_success
    end

    it "should have a form to edit the house's details" do
      get 'edit', :id => @house.id
      page.should have_selector "form"
    end

    it "should be prefilled with the houses details" do
      get 'edit', :id => @house
      page.should have_selector "input#house_title", :value => @house.title
    end
  end

  describe "POST create" do
    describe "with valid params" do
      before(:each) do
        @attr = {
          :title => "This is the title of a house",
          :description => "This is the description of a house",
          :image_url => 'http://mediacache-s3eu.daft.ie/MZYU1EHKU5Wezk5xuw07WPdRb8VZeof6esL9j1djM-RtPWRhZnQmZT0xNjB4MTIw.jpg',

          :number => 23,
          :street => 'Main Street',
          :town => 'Drogheda',
          :county_id => 4,

          :price => 200_000,
          :bedrooms => 4,
        }
      end

      it "should add a house to the DB" do
        expect {
          post 'create', :house => @attr
        }.to change(House, :count).by(1)
      end

      it "redirects to the created house" do
        post 'create', :house => @attr
        response.should redirect_to(house_url(assigns :house))
      end
    end

    describe "with invalid params" do
      before(:each) do
        @attr = {
          :title => "",
          :description => "",
          :image_url => '',

          :number => nil,
          :street => '',
          :town => '',
          :county_id => nil,

          :price => nil,
          :bedrooms => nil,
        }
      end

      it "should not create a DB record" do
        expect {
          post 'create', :house => @attr
        }.to change(House, :count).by(0)
      end

      it "should re-render the 'new' template" do
        post "create", :house => @attr
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    before(:each) do
      @house = Factory :house
    end
    
    describe "with valid params" do
      before(:each) do
        @attr = {
          :title => "This is the other title of a house",
          :description => "This is the description of a house",
          :image_url => 'http://mediacache-s3eu.daft.ie/MZYU1EHKU5Wezk5xuw07WPdRb8VZeof6esL9j1djM-RtPWRhZnQmZT0xNjB4MTIw.jpg',

          :number => 23,
          :street => 'Not Main Street',
          :town => 'Drogheda',
          :county_id => 4,

          :price => 200_000,
          :bedrooms => 4,
        }
      end

      it "updates the requested house" do
        put 'update', :id => @house, :house => @attr

        @house.reload
        @house.title.should  == @attr[:title]
        @house.street.should == @attr[:street]
      end

      it "redirects to the house" do
        put 'update', :id => @house, :house => @attr
        response.should redirect_to(house_path(@house))
      end
    end

    describe "with invalid params" do
      before(:each) do
        @attr = {
          :title => "",
          :description => "",
          :image_url => '',

          :number => nil,
          :street => '',
          :town => '',
          :county_id => nil,

          :price => nil,
          :bedrooms => nil,
        }
      end

      it "should re-render the edit template" do
        put 'update', :id => @house, :house => @attr
        response.should render_template('edit')
      end
    end
  end

#  1. Action name must be supplied as a string. Not a path
#  2. You don't need the :js => true
#  3. You can leave off the .id from @house.id
  describe "DELETE destroy" do
    before(:each) do
      @house = Factory :house
    end

    it "destroys the requested house" do
      expect {
        delete 'destroy', :id => @house
      }.to change(House, :count).by(-1)
    end

    it "redirects to the houses list" do
      delete 'destroy', :id => @house
      response.should redirect_to(houses_path)
    end
  end

end
